api = "0.7"

[buildpack]
  description = "A buildpack for installing the appropriate Nginx server"
  homepage = "https://github.com/paketo-buildpacks/nginx"
  id = "paketo-buildpacks/nginx"
  keywords = ["nginx", "server", "distribution"]
  name = "Paketo Buildpack for Nginx Server"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/configure", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run", "linux/amd64/bin/configure"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"
  [metadata.default-versions]
    nginx = "1.29.*"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:ada6df892c7ae35ffa32f0224b10fdaf93360717ffb7cde4f88c9aa4359522d5"
    cpe = "cpe:2.3:a:nginx:nginx:1.29.5:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.29.5?checksum=6744768a4114880f37b13a0443244e731bcb3130c0a065d7e37d8fd589ade374&download_url=https://nginx.org/download/nginx-1.29.5.tar.gz"
    source = "https://nginx.org/download/nginx-1.29.5.tar.gz"
    source-checksum = "sha256:6744768a4114880f37b13a0443244e731bcb3130c0a065d7e37d8fd589ade374"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.29.5_linux_amd64_jammy_ada6df89.tgz"
    version = "1.29.5"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:dcd70900e08a36a42c35b7cff5dc32424a8bc77c47280e48bd869ae172bd2f88"
    cpe = "cpe:2.3:a:nginx:nginx:1.29.5:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.29.5?checksum=6744768a4114880f37b13a0443244e731bcb3130c0a065d7e37d8fd589ade374&download_url=https://nginx.org/download/nginx-1.29.5.tar.gz"
    source = "https://nginx.org/download/nginx-1.29.5.tar.gz"
    source-checksum = "sha256:6744768a4114880f37b13a0443244e731bcb3130c0a065d7e37d8fd589ade374"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.29.5_linux_arm64_jammy_dcd70900.tgz"
    version = "1.29.5"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:937f1030f59b4c9338d1f71ae06ad11c8b833d70d5ccab7486798912745b5c8d"
    cpe = "cpe:2.3:a:nginx:nginx:1.29.5:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.29.5?checksum=6744768a4114880f37b13a0443244e731bcb3130c0a065d7e37d8fd589ade374&download_url=https://nginx.org/download/nginx-1.29.5.tar.gz"
    source = "https://nginx.org/download/nginx-1.29.5.tar.gz"
    source-checksum = "sha256:6744768a4114880f37b13a0443244e731bcb3130c0a065d7e37d8fd589ade374"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.29.5_linux_amd64_noble_937f1030.tgz"
    version = "1.29.5"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:16b2519c65899776f407875f3f2364200a738bd9d960004a797d5d34bd3cfbcf"
    cpe = "cpe:2.3:a:nginx:nginx:1.29.5:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.29.5?checksum=6744768a4114880f37b13a0443244e731bcb3130c0a065d7e37d8fd589ade374&download_url=https://nginx.org/download/nginx-1.29.5.tar.gz"
    source = "https://nginx.org/download/nginx-1.29.5.tar.gz"
    source-checksum = "sha256:6744768a4114880f37b13a0443244e731bcb3130c0a065d7e37d8fd589ade374"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.29.5_linux_arm64_noble_16b2519c.tgz"
    version = "1.29.5"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:4e60a2107ffde2098824bec232f9bc6c9561c73c47c26cf210c5f6607d1cc09b"
    cpe = "cpe:2.3:a:nginx:nginx:1.29.6:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.29.6?checksum=316f298cd9f061d6d0679696152710285b72f75d88eb1f7e323f40c5c52fe0d7&download_url=https://nginx.org/download/nginx-1.29.6.tar.gz"
    source = "https://nginx.org/download/nginx-1.29.6.tar.gz"
    source-checksum = "sha256:316f298cd9f061d6d0679696152710285b72f75d88eb1f7e323f40c5c52fe0d7"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.29.6_linux_amd64_jammy_4e60a210.tgz"
    version = "1.29.6"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:e13fecbec125e7f2028fa80bcb4e5f202247feda25559bcd8f65a7022463ff7d"
    cpe = "cpe:2.3:a:nginx:nginx:1.29.6:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.29.6?checksum=316f298cd9f061d6d0679696152710285b72f75d88eb1f7e323f40c5c52fe0d7&download_url=https://nginx.org/download/nginx-1.29.6.tar.gz"
    source = "https://nginx.org/download/nginx-1.29.6.tar.gz"
    source-checksum = "sha256:316f298cd9f061d6d0679696152710285b72f75d88eb1f7e323f40c5c52fe0d7"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.29.6_linux_arm64_jammy_e13fecbe.tgz"
    version = "1.29.6"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:2110190ea4f3b2eac93776315730ea340e15e232d391c629dbe605f2c67e3ed0"
    cpe = "cpe:2.3:a:nginx:nginx:1.29.6:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.29.6?checksum=316f298cd9f061d6d0679696152710285b72f75d88eb1f7e323f40c5c52fe0d7&download_url=https://nginx.org/download/nginx-1.29.6.tar.gz"
    source = "https://nginx.org/download/nginx-1.29.6.tar.gz"
    source-checksum = "sha256:316f298cd9f061d6d0679696152710285b72f75d88eb1f7e323f40c5c52fe0d7"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.29.6_linux_amd64_noble_2110190e.tgz"
    version = "1.29.6"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:2046806263b8b84e4b5f0f98088c8f3ab363d70b1c19b07247813111d4802279"
    cpe = "cpe:2.3:a:nginx:nginx:1.29.6:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.29.6?checksum=316f298cd9f061d6d0679696152710285b72f75d88eb1f7e323f40c5c52fe0d7&download_url=https://nginx.org/download/nginx-1.29.6.tar.gz"
    source = "https://nginx.org/download/nginx-1.29.6.tar.gz"
    source-checksum = "sha256:316f298cd9f061d6d0679696152710285b72f75d88eb1f7e323f40c5c52fe0d7"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.29.6_linux_arm64_noble_20468062.tgz"
    version = "1.29.6"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:dda6699496b45978dcf037c9d5d34b8e293b1dbcc64d0f5edd12527bc62e1a27"
    cpe = "cpe:2.3:a:nginx:nginx:1.28.1:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.28.1?checksum=40e7a0916d121e8905ef50f2a738b675599e42b2224a582dd938603fed15788e&download_url=https://nginx.org/download/nginx-1.28.1.tar.gz"
    source = "https://nginx.org/download/nginx-1.28.1.tar.gz"
    source-checksum = "sha256:40e7a0916d121e8905ef50f2a738b675599e42b2224a582dd938603fed15788e"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.28.1_linux_amd64_jammy_dda66994.tgz"
    version = "1.28.1"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:20c2cdcc1032d12d8a3d0964e8a41f95af690019430407bd2f75dc2abf3a8bda"
    cpe = "cpe:2.3:a:nginx:nginx:1.28.1:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.28.1?checksum=40e7a0916d121e8905ef50f2a738b675599e42b2224a582dd938603fed15788e&download_url=https://nginx.org/download/nginx-1.28.1.tar.gz"
    source = "https://nginx.org/download/nginx-1.28.1.tar.gz"
    source-checksum = "sha256:40e7a0916d121e8905ef50f2a738b675599e42b2224a582dd938603fed15788e"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.28.1_linux_arm64_jammy_20c2cdcc.tgz"
    version = "1.28.1"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:f563d8ee00cc27445dd7f6518c144b461b5aa49940a2a5add8020379c67f7c48"
    cpe = "cpe:2.3:a:nginx:nginx:1.28.1:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.28.1?checksum=40e7a0916d121e8905ef50f2a738b675599e42b2224a582dd938603fed15788e&download_url=https://nginx.org/download/nginx-1.28.1.tar.gz"
    source = "https://nginx.org/download/nginx-1.28.1.tar.gz"
    source-checksum = "sha256:40e7a0916d121e8905ef50f2a738b675599e42b2224a582dd938603fed15788e"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.28.1_linux_amd64_noble_f563d8ee.tgz"
    version = "1.28.1"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:cb12f9d2e289d13425b8288271cab14a7b0e050b934f2211ac5ae9e1801060fb"
    cpe = "cpe:2.3:a:nginx:nginx:1.28.1:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.28.1?checksum=40e7a0916d121e8905ef50f2a738b675599e42b2224a582dd938603fed15788e&download_url=https://nginx.org/download/nginx-1.28.1.tar.gz"
    source = "https://nginx.org/download/nginx-1.28.1.tar.gz"
    source-checksum = "sha256:40e7a0916d121e8905ef50f2a738b675599e42b2224a582dd938603fed15788e"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.28.1_linux_arm64_noble_cb12f9d2.tgz"
    version = "1.28.1"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:108a8230072205f0b86d5eb51221dd4b93d9c9e2fc3ad01acb832fbf7ee8c4d0"
    cpe = "cpe:2.3:a:nginx:nginx:1.28.2:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.28.2?checksum=20e5e0f2c917acfb51120eec2fba9a4ba4e1e10fd28465067cc87a7d81a829a3&download_url=https://nginx.org/download/nginx-1.28.2.tar.gz"
    source = "https://nginx.org/download/nginx-1.28.2.tar.gz"
    source-checksum = "sha256:20e5e0f2c917acfb51120eec2fba9a4ba4e1e10fd28465067cc87a7d81a829a3"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.28.2_linux_amd64_jammy_108a8230.tgz"
    version = "1.28.2"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:c57e0b46f4cc452b889d289da90de44ebbfabf7978a5a3aac1c7618f5e904100"
    cpe = "cpe:2.3:a:nginx:nginx:1.28.2:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.28.2?checksum=20e5e0f2c917acfb51120eec2fba9a4ba4e1e10fd28465067cc87a7d81a829a3&download_url=https://nginx.org/download/nginx-1.28.2.tar.gz"
    source = "https://nginx.org/download/nginx-1.28.2.tar.gz"
    source-checksum = "sha256:20e5e0f2c917acfb51120eec2fba9a4ba4e1e10fd28465067cc87a7d81a829a3"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.28.2_linux_arm64_jammy_c57e0b46.tgz"
    version = "1.28.2"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:07e82b0f317f1d54a643cc93f46e16c428e4b36f856e066e99a455d1352e5d64"
    cpe = "cpe:2.3:a:nginx:nginx:1.28.2:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.28.2?checksum=20e5e0f2c917acfb51120eec2fba9a4ba4e1e10fd28465067cc87a7d81a829a3&download_url=https://nginx.org/download/nginx-1.28.2.tar.gz"
    source = "https://nginx.org/download/nginx-1.28.2.tar.gz"
    source-checksum = "sha256:20e5e0f2c917acfb51120eec2fba9a4ba4e1e10fd28465067cc87a7d81a829a3"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.28.2_linux_amd64_noble_07e82b0f.tgz"
    version = "1.28.2"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:ab639801e971cfd4f1c62184c7ff98e5b81f42756c49ca797dfa4005753cf422"
    cpe = "cpe:2.3:a:nginx:nginx:1.28.2:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.28.2?checksum=20e5e0f2c917acfb51120eec2fba9a4ba4e1e10fd28465067cc87a7d81a829a3&download_url=https://nginx.org/download/nginx-1.28.2.tar.gz"
    source = "https://nginx.org/download/nginx-1.28.2.tar.gz"
    source-checksum = "sha256:20e5e0f2c917acfb51120eec2fba9a4ba4e1e10fd28465067cc87a7d81a829a3"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.28.2_linux_arm64_noble_ab639801.tgz"
    version = "1.28.2"

  [[metadata.dependency-constraints]]
    constraint = "1.29.*"
    id = "nginx"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "1.28.*"
    id = "nginx"
    patches = 2
  [metadata.version-lines]
    mainline = "1.29.*"
    stable = "1.28.*"

[[stacks]]
  id = "io.buildpacks.stacks.jammy"

[[stacks]]
  id = "io.buildpacks.stacks.noble"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
