api = "0.7"

[buildpack]
  description = "A buildpack for installing the appropriate Nginx server"
  homepage = "https://github.com/paketo-buildpacks/nginx"
  id = "paketo-buildpacks/nginx"
  keywords = ["nginx", "server", "distribution"]
  name = "Paketo Buildpack for Nginx Server"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/configure", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run", "linux/amd64/bin/configure"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"
  [metadata.default-versions]
    nginx = "1.29.*"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:c49aed784ba1876f70602e4df87ecdc982e823ee63a931fe2ecbdc79727cfde5"
    cpe = "cpe:2.3:a:nginx:nginx:1.29.7:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.29.7?checksum=673f8fb8c0961c44fbd9410d6161831453609b44063d3f2948253fc2b5692139&download_url=https://nginx.org/download/nginx-1.29.7.tar.gz"
    source = "https://nginx.org/download/nginx-1.29.7.tar.gz"
    source-checksum = "sha256:673f8fb8c0961c44fbd9410d6161831453609b44063d3f2948253fc2b5692139"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.29.7_linux_amd64_jammy_c49aed78.tgz"
    version = "1.29.7"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:14f908022fba964bc1809a6697de5bb8ef0e755d7f1ab3c23e917fe3f9ee6009"
    cpe = "cpe:2.3:a:nginx:nginx:1.29.7:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.29.7?checksum=673f8fb8c0961c44fbd9410d6161831453609b44063d3f2948253fc2b5692139&download_url=https://nginx.org/download/nginx-1.29.7.tar.gz"
    source = "https://nginx.org/download/nginx-1.29.7.tar.gz"
    source-checksum = "sha256:673f8fb8c0961c44fbd9410d6161831453609b44063d3f2948253fc2b5692139"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.29.7_linux_arm64_jammy_14f90802.tgz"
    version = "1.29.7"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:a8ba339618095a2e7cfd6a9234a12d90daeae021b8d123df4a61a507527ec4a3"
    cpe = "cpe:2.3:a:nginx:nginx:1.29.7:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.29.7?checksum=673f8fb8c0961c44fbd9410d6161831453609b44063d3f2948253fc2b5692139&download_url=https://nginx.org/download/nginx-1.29.7.tar.gz"
    source = "https://nginx.org/download/nginx-1.29.7.tar.gz"
    source-checksum = "sha256:673f8fb8c0961c44fbd9410d6161831453609b44063d3f2948253fc2b5692139"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.29.7_linux_amd64_noble_a8ba3396.tgz"
    version = "1.29.7"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:33e75734171c6d0f0a85ff2288e97f60041a7608b605d286bac0b257e23564c9"
    cpe = "cpe:2.3:a:nginx:nginx:1.29.7:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.29.7?checksum=673f8fb8c0961c44fbd9410d6161831453609b44063d3f2948253fc2b5692139&download_url=https://nginx.org/download/nginx-1.29.7.tar.gz"
    source = "https://nginx.org/download/nginx-1.29.7.tar.gz"
    source-checksum = "sha256:673f8fb8c0961c44fbd9410d6161831453609b44063d3f2948253fc2b5692139"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.29.7_linux_arm64_noble_33e75734.tgz"
    version = "1.29.7"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:0a716708a57462b89110f49097b4b5d3f457fc8e2704c1a97846eaf8ff7d2a62"
    cpe = "cpe:2.3:a:nginx:nginx:1.29.8:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.29.8?checksum=7f1b985dace8fe706dfc288b83927c928f0ae60bcb7507c2d4e0025eca7280c3&download_url=https://nginx.org/download/nginx-1.29.8.tar.gz"
    source = "https://nginx.org/download/nginx-1.29.8.tar.gz"
    source-checksum = "sha256:7f1b985dace8fe706dfc288b83927c928f0ae60bcb7507c2d4e0025eca7280c3"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.29.8_linux_amd64_jammy_0a716708.tgz"
    version = "1.29.8"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:b1c5edc019821d6b5b603b83862f4eb05dab89969bf96974033eaba5bcf81f8f"
    cpe = "cpe:2.3:a:nginx:nginx:1.29.8:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.29.8?checksum=7f1b985dace8fe706dfc288b83927c928f0ae60bcb7507c2d4e0025eca7280c3&download_url=https://nginx.org/download/nginx-1.29.8.tar.gz"
    source = "https://nginx.org/download/nginx-1.29.8.tar.gz"
    source-checksum = "sha256:7f1b985dace8fe706dfc288b83927c928f0ae60bcb7507c2d4e0025eca7280c3"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.29.8_linux_arm64_jammy_b1c5edc0.tgz"
    version = "1.29.8"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:11c890e30354870165a81835d5695a815f34fc4bdcd6482821358f60abf97bb1"
    cpe = "cpe:2.3:a:nginx:nginx:1.29.8:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.29.8?checksum=7f1b985dace8fe706dfc288b83927c928f0ae60bcb7507c2d4e0025eca7280c3&download_url=https://nginx.org/download/nginx-1.29.8.tar.gz"
    source = "https://nginx.org/download/nginx-1.29.8.tar.gz"
    source-checksum = "sha256:7f1b985dace8fe706dfc288b83927c928f0ae60bcb7507c2d4e0025eca7280c3"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.29.8_linux_amd64_noble_11c890e3.tgz"
    version = "1.29.8"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:ad046b7efe9031c6ef384f90af494f319f4bdafc1c007b68698fcd0580b8a0b8"
    cpe = "cpe:2.3:a:nginx:nginx:1.29.8:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.29.8?checksum=7f1b985dace8fe706dfc288b83927c928f0ae60bcb7507c2d4e0025eca7280c3&download_url=https://nginx.org/download/nginx-1.29.8.tar.gz"
    source = "https://nginx.org/download/nginx-1.29.8.tar.gz"
    source-checksum = "sha256:7f1b985dace8fe706dfc288b83927c928f0ae60bcb7507c2d4e0025eca7280c3"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.29.8_linux_arm64_noble_ad046b7e.tgz"
    version = "1.29.8"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:108a8230072205f0b86d5eb51221dd4b93d9c9e2fc3ad01acb832fbf7ee8c4d0"
    cpe = "cpe:2.3:a:nginx:nginx:1.28.2:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.28.2?checksum=20e5e0f2c917acfb51120eec2fba9a4ba4e1e10fd28465067cc87a7d81a829a3&download_url=https://nginx.org/download/nginx-1.28.2.tar.gz"
    source = "https://nginx.org/download/nginx-1.28.2.tar.gz"
    source-checksum = "sha256:20e5e0f2c917acfb51120eec2fba9a4ba4e1e10fd28465067cc87a7d81a829a3"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.28.2_linux_amd64_jammy_108a8230.tgz"
    version = "1.28.2"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:c57e0b46f4cc452b889d289da90de44ebbfabf7978a5a3aac1c7618f5e904100"
    cpe = "cpe:2.3:a:nginx:nginx:1.28.2:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.28.2?checksum=20e5e0f2c917acfb51120eec2fba9a4ba4e1e10fd28465067cc87a7d81a829a3&download_url=https://nginx.org/download/nginx-1.28.2.tar.gz"
    source = "https://nginx.org/download/nginx-1.28.2.tar.gz"
    source-checksum = "sha256:20e5e0f2c917acfb51120eec2fba9a4ba4e1e10fd28465067cc87a7d81a829a3"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.28.2_linux_arm64_jammy_c57e0b46.tgz"
    version = "1.28.2"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:07e82b0f317f1d54a643cc93f46e16c428e4b36f856e066e99a455d1352e5d64"
    cpe = "cpe:2.3:a:nginx:nginx:1.28.2:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.28.2?checksum=20e5e0f2c917acfb51120eec2fba9a4ba4e1e10fd28465067cc87a7d81a829a3&download_url=https://nginx.org/download/nginx-1.28.2.tar.gz"
    source = "https://nginx.org/download/nginx-1.28.2.tar.gz"
    source-checksum = "sha256:20e5e0f2c917acfb51120eec2fba9a4ba4e1e10fd28465067cc87a7d81a829a3"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.28.2_linux_amd64_noble_07e82b0f.tgz"
    version = "1.28.2"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:ab639801e971cfd4f1c62184c7ff98e5b81f42756c49ca797dfa4005753cf422"
    cpe = "cpe:2.3:a:nginx:nginx:1.28.2:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.28.2?checksum=20e5e0f2c917acfb51120eec2fba9a4ba4e1e10fd28465067cc87a7d81a829a3&download_url=https://nginx.org/download/nginx-1.28.2.tar.gz"
    source = "https://nginx.org/download/nginx-1.28.2.tar.gz"
    source-checksum = "sha256:20e5e0f2c917acfb51120eec2fba9a4ba4e1e10fd28465067cc87a7d81a829a3"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.28.2_linux_arm64_noble_ab639801.tgz"
    version = "1.28.2"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:053a8a3a0d2e8edf33e3696aaa21fa7497430f7f67755c82198ab491dfcccdde"
    cpe = "cpe:2.3:a:nginx:nginx:1.28.3:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.28.3?checksum=2c96a946bfb0882a21744ed429770a2123ae1828c7c48665092993ddee91a918&download_url=https://nginx.org/download/nginx-1.28.3.tar.gz"
    source = "https://nginx.org/download/nginx-1.28.3.tar.gz"
    source-checksum = "sha256:2c96a946bfb0882a21744ed429770a2123ae1828c7c48665092993ddee91a918"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.28.3_linux_amd64_jammy_053a8a3a.tgz"
    version = "1.28.3"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:d20d89d81e29cd16ee6575c28c39220137b5e8b007a6492e8b92a2b7464728c9"
    cpe = "cpe:2.3:a:nginx:nginx:1.28.3:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.28.3?checksum=2c96a946bfb0882a21744ed429770a2123ae1828c7c48665092993ddee91a918&download_url=https://nginx.org/download/nginx-1.28.3.tar.gz"
    source = "https://nginx.org/download/nginx-1.28.3.tar.gz"
    source-checksum = "sha256:2c96a946bfb0882a21744ed429770a2123ae1828c7c48665092993ddee91a918"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.28.3_linux_arm64_jammy_d20d89d8.tgz"
    version = "1.28.3"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:720d0fc089ede3a02ed81c3eb78445e5eed5c9f52ca83154b2c5cfe615b74270"
    cpe = "cpe:2.3:a:nginx:nginx:1.28.3:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.28.3?checksum=2c96a946bfb0882a21744ed429770a2123ae1828c7c48665092993ddee91a918&download_url=https://nginx.org/download/nginx-1.28.3.tar.gz"
    source = "https://nginx.org/download/nginx-1.28.3.tar.gz"
    source-checksum = "sha256:2c96a946bfb0882a21744ed429770a2123ae1828c7c48665092993ddee91a918"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.28.3_linux_amd64_noble_720d0fc0.tgz"
    version = "1.28.3"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:2af64c15c383c98720546ab470d9109f9f81f631d3c5fb88e0c5a2363aca83e8"
    cpe = "cpe:2.3:a:nginx:nginx:1.28.3:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "nginx"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD"]
    name = "Nginx Server"
    os = "linux"
    purl = "pkg:generic/nginx@1.28.3?checksum=2c96a946bfb0882a21744ed429770a2123ae1828c7c48665092993ddee91a918&download_url=https://nginx.org/download/nginx-1.28.3.tar.gz"
    source = "https://nginx.org/download/nginx-1.28.3.tar.gz"
    source-checksum = "sha256:2c96a946bfb0882a21744ed429770a2123ae1828c7c48665092993ddee91a918"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.28.3_linux_arm64_noble_2af64c15.tgz"
    version = "1.28.3"

  [[metadata.dependency-constraints]]
    constraint = "1.29.*"
    id = "nginx"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "1.28.*"
    id = "nginx"
    patches = 2
  [metadata.version-lines]
    mainline = "1.29.*"
    stable = "1.28.*"

[[stacks]]
  id = "io.buildpacks.stacks.jammy"

[[stacks]]
  id = "io.buildpacks.stacks.noble"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
