# This composite action works when called from a workflow that has qemu and buildkit set up.
# Docker daemon and cli experimental features must also be enabled.
# Compilation is slow when run on emulated platforms, so the .github/workflows/compile-dependency.yml
# reusable workflow is used instead of this composite action. This is left here for reference.
name: 'Compile NGINX on Target'
description: |
  Compiles NGINX given a version, output directory, and a target image to compile on

inputs:
  version:
    description: 'dependency version'
    required: true
  outputDir:
    description: 'output directory'
    required: true
  target:
    description: 'dependency OS target variant'
    required: true
  os:
    description: 'platform OS (e.g., linux)'
    required: true
  arch:
    description: 'platform architecture (e.g., amd64)'
    required: true

runs:
  using: 'composite'
  steps:

  - name: build compilation
    id: build-compilation
    shell: bash
    run: docker build --platform ${{ inputs.os }}/${{ inputs.arch }} -t compilation -f dependency/actions/compile/${{ inputs.target }}.Dockerfile dependency/actions/compile

  - name: run compilation
    id: run-compilation
    shell: bash
    run: docker run --platform ${{ inputs.os }}/${{ inputs.arch }} -v ${{ inputs.outputDir }}:/home compilation --version ${{ inputs.version }} --outputDir /home --target ${{ inputs.target }}

  - name: print contents of output dir
    shell: bash
    run: ls -lah ${{ inputs.outputDir }}

  - name: build test
    id: build-test
    shell: bash
    run: docker build --platform ${{ inputs.os }}/${{ inputs.arch }} -t test -f dependency/test/${{ inputs.target }}/Dockerfile dependency/test/${{ inputs.target }}

  - name: run test
    id: run-test
    shell: bash
    run: docker run --platform ${{ inputs.os }}/${{ inputs.arch }} -v ${{ inputs.outputDir }}:/tarball_path test --version ${{ inputs.version }}
